### PR TITLE
Add instructions on reverting card to original state

### PR DESCRIPTION
**Pull request by njhughes-01**
Added instructions in case anyone else upgrade to 5g or 8g service.

### CODE REVIEW

**Comment by Berzerker** [comment]
Thanks! Could you add some language (just a sentence or two) before that to indicate these instructions were added to anticipate people wanting to revert the port back to 10Gb for the new 5/8Gb service? I get people would think about that regardless, but would flow a bit better in the readme.

**Comment by Killerherts** [comment]
Np LMK if you would like me to add a bit more

**Comment by Berzerker** [comment]
Added some comments on the commit for some small changes

**Comment by Berzerker** [comment]
Thanks!

**Pull request merged**
